apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: news
build:
  artifacts:
  - image: ghcr.io/cobbles/news/news-app
    context: app
    docker:
      dockerfile: Dockerfile
      target: prod
    sync:
      manual:
      - src: '**/*'
        dest: '.'
deploy:
  kustomize:
    paths:
    - k8s/bases/news-app

profiles:
- name: dev
  activation:
  - command: dev
  patches:
  - op: replace
    path: /build/artifacts/0/docker/target
    value: dev
